Repository baynezy/Html2Markdown, pull requests merged in 2023-12, with the labels that each got.

#327 Upgrade to .Net 8
  .cm/gitstream.cm
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/blocked-issue.yml
  .github/workflows/branch-develop.yml
  .github/workflows/branch-feature.yml
  .github/workflows/branch-hotfix.yml
  .github/workflows/branch-master.yml
  .github/workflows/branch-release.yml
  .github/workflows/completed-feature-workflow.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/in-progress-feature-workflow.yml
  .github/workflows/label-configurer.yml
  .github/workflows/new-issue-workflow.yml
  .github/workflows/step-build.yml
  .github/workflows/step-check-markdown.yml
  .github/workflows/step-publish-package.yml
  .github/workflows/step-publish.yml
  .github/workflows/step-tag-release.yml
  .github/workflows/step-version.yml
  .github/workflows/test-dependabot.yml
  CHANGELOG.md
  Html2Markdown.sln
  appveyor.yml
  build.cake
  semver.json
  src/Html2Markdown/Html2Markdown.csproj
  test/Html2Markdown.Test/Html2Markdown.Test.csproj
Labels: cm-changes

#338 Utiilse .Net 7 capabilities
  src/Html2Markdown/Converter.cs
  src/Html2Markdown/GlobalUsings.cs
  src/Html2Markdown/HtmlAgilityPackExtensions.cs
  src/Html2Markdown/Replacement/CustomReplacer.cs
  src/Html2Markdown/Replacement/EntitiesReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadingReplacementGroup.cs
  src/Html2Markdown/Replacement/HtmlParser.cs
  src/Html2Markdown/Replacement/IReplacer.cs
  src/Html2Markdown/Replacement/IReplacerGroup.cs
  src/Html2Markdown/Replacement/IllegalHtmlReplacementGroup.cs
  src/Html2Markdown/Replacement/LayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/PatternReplacer.cs
  src/Html2Markdown/Replacement/TextFormattingReplacementGroup.cs
  src/Html2Markdown/Scheme/AbstractScheme.cs
  src/Html2Markdown/Scheme/IScheme.cs
  src/Html2Markdown/Scheme/Markdown.cs
  test/Html2Markdown.Test/ConvertFromFileTest.cs
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: 30 min review

#340 Fix issues in README
  README.md
Labels: 1 min review

#341 Fix NuGet license issue
  Html2Markdown.sln
  src/Html2Markdown/Html2Markdown.csproj
Labels: 1 min review

#343 Release version 6.0.0.1
  .cm/gitstream.cm
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/blocked-issue.yml
  .github/workflows/branch-develop.yml
  .github/workflows/branch-feature.yml
  .github/workflows/branch-hotfix.yml
  .github/workflows/branch-master.yml
  .github/workflows/branch-release.yml
  .github/workflows/completed-feature-workflow.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/gitstream.yml
  .github/workflows/in-progress-feature-workflow.yml
  .github/workflows/label-configurer.yml
  .github/workflows/new-issue-workflow.yml
  .github/workflows/step-build.yml
  .github/workflows/step-check-markdown.yml
  .github/workflows/step-publish-package.yml
  .github/workflows/step-publish.yml
  .github/workflows/step-tag-release.yml
  .github/workflows/step-version.yml
  .github/workflows/test-dependabot.yml
  CHANGELOG.md
  Html2Markdown.sln
  README.md
  appveyor.yml
  build.cake
  semver.json
  src/Html2Markdown/Converter.cs
  src/Html2Markdown/GlobalUsings.cs
  src/Html2Markdown/Html2Markdown.csproj
  src/Html2Markdown/HtmlAgilityPackExtensions.cs
  src/Html2Markdown/Replacement/CustomReplacer.cs
  src/Html2Markdown/Replacement/EntitiesReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadingReplacementGroup.cs
  src/Html2Markdown/Replacement/HtmlParser.cs
  src/Html2Markdown/Replacement/IReplacer.cs
  src/Html2Markdown/Replacement/IReplacerGroup.cs
  src/Html2Markdown/Replacement/IllegalHtmlReplacementGroup.cs
  src/Html2Markdown/Replacement/LayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/PatternReplacer.cs
  src/Html2Markdown/Replacement/TextFormattingReplacementGroup.cs
  src/Html2Markdown/Scheme/AbstractScheme.cs
  src/Html2Markdown/Scheme/IScheme.cs
  src/Html2Markdown/Scheme/Markdown.cs
  test/Html2Markdown.Test/ConvertFromFileTest.cs
  test/Html2Markdown.Test/Html2Markdown.Test.csproj
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_Bug269.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenAListHasNoItems_ThenRemoveTheList.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: cm-changes

#344 Merge master into develop branch
  CHANGELOG.md
  semver.json
Labels: 1 min review

#346 Fix issue with image src for master build status
  README.md
Labels: 1 min review

#347 Support syntax highlighting for code blocks
  src/Html2Markdown/Replacement/HtmlParser.cs
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereMultilineCodeTagsWithSyntaxHighlight_ThenReplaceWithMultilineMarkdownBlock001.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereMultilineCodeTagsWithSyntaxHighlight_ThenReplaceWithMultilineMarkdownBlock002.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereMultilineCodeTagsWithSyntaxHighlight_ThenReplaceWithMultilineMarkdownBlock003.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: awaiting feedback, 5 min review

#351 Merge master into develop branch
  CHANGELOG.md
  semver.json
Labels: 1 min review

#353 Add stale issue workflow
  .github/labels.yml
  .github/workflows/stale-issues-prs.yml
Labels: 1 min review

#361 Allow strong and b tags to have properties
  .gitignore
  .idea/.idea.Html2Markdown/.idea/.gitignore
  .idea/.idea.Html2Markdown/.idea/encodings.xml
  .idea/.idea.Html2Markdown/.idea/indexLayout.xml
  .idea/.idea.Html2Markdown/.idea/vcs.xml
  src/Html2Markdown/Replacement/TextFormattingReplacementGroup.cs
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsABoldTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAStrongTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsABoldTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAStrongTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: 1 min review

#363 Create concrete implementations of replacers
  src/Html2Markdown/Converter.cs
  src/Html2Markdown/Replacement/AnchorTagReplacer.cs
  src/Html2Markdown/Replacement/BlockquoteTagReplacer.cs
  src/Html2Markdown/Replacement/BodyTagReplacer.cs
  src/Html2Markdown/Replacement/BreakTagReplacer.cs
  src/Html2Markdown/Replacement/CodeTagReplacer.cs
  src/Html2Markdown/Replacement/CommonMark/CommonMarkLayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/CompositeReplacer.cs
  src/Html2Markdown/Replacement/CustomReplacer.cs
  src/Html2Markdown/Replacement/DocTypeReplacer.cs
  src/Html2Markdown/Replacement/EmphasisTagReplacer.cs
  src/Html2Markdown/Replacement/EntitiesReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadTagReplacer.cs
  src/Html2Markdown/Replacement/Heading.cs
  src/Html2Markdown/Replacement/HeadingReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadingTagReplacer.cs
  src/Html2Markdown/Replacement/HorizontalRuleTagReplacer.cs
  src/Html2Markdown/Replacement/HtmlCommentReplacer.cs
  src/Html2Markdown/Replacement/HtmlEntitiesReplacer.cs
  src/Html2Markdown/Replacement/HtmlListReplacer.cs
  src/Html2Markdown/Replacement/HtmlTagReplacer.cs
  src/Html2Markdown/Replacement/IllegalHtmlReplacementGroup.cs
  src/Html2Markdown/Replacement/ImageTagReplacer.cs
  src/Html2Markdown/Replacement/LayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/LinkTagReplacer.cs
  src/Html2Markdown/Replacement/MetaTagReplacer.cs
  src/Html2Markdown/Replacement/ParagraphTagReplacer.cs
  src/Html2Markdown/Replacement/PatternReplacer.cs
  src/Html2Markdown/Replacement/PreTagReplacer.cs
  src/Html2Markdown/Replacement/ScriptTagReplacer.cs
  src/Html2Markdown/Replacement/StrongTagReplacer.cs
  src/Html2Markdown/Replacement/TextFormattingReplacementGroup.cs
  src/Html2Markdown/Replacement/TitleTagReplacer.cs
  src/Html2Markdown/Scheme/Markdown.cs
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAParagraphTagAfterAList_ThenThereShouldBeAppropriateSpacing.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithANestedUnorderedList_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAParagraphTagAfterAList_ThenThereShouldBeAppropriateSpacing.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithANestedUnorderedList_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: 20 min review

#364 Remove extra whitespace on lists containing p tags
  src/Html2Markdown/Replacement/CodeTagReplacer.cs
  src/Html2Markdown/Replacement/CustomReplacer.cs
  src/Html2Markdown/Replacement/HtmlParser.cs
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAMultilineOrderedListWithNestedParagraphsAndCodeElement_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithNestedParagraphs_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAMultilineOrderedListWithNestedParagraphsAndCodeElement_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithNestedParagraphs_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: 1 min review

#365 Release version 6.2.0.3
  .github/labels.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/step-build.yml
  .github/workflows/step-publish-package.yml
  .gitignore
  .idea/.idea.Html2Markdown/.idea/.gitignore
  .idea/.idea.Html2Markdown/.idea/encodings.xml
  .idea/.idea.Html2Markdown/.idea/indexLayout.xml
  .idea/.idea.Html2Markdown/.idea/vcs.xml
  CHANGELOG.md
  semver.json
  src/Html2Markdown/Converter.cs
  src/Html2Markdown/Html2Markdown.csproj
  src/Html2Markdown/Replacement/AnchorTagReplacer.cs
  src/Html2Markdown/Replacement/BlockquoteTagReplacer.cs
  src/Html2Markdown/Replacement/BodyTagReplacer.cs
  src/Html2Markdown/Replacement/BreakTagReplacer.cs
  src/Html2Markdown/Replacement/CodeTagReplacer.cs
  src/Html2Markdown/Replacement/CommonMark/CommonMarkLayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/CompositeReplacer.cs
  src/Html2Markdown/Replacement/CustomReplacer.cs
  src/Html2Markdown/Replacement/DocTypeReplacer.cs
  src/Html2Markdown/Replacement/EmphasisTagReplacer.cs
  src/Html2Markdown/Replacement/EntitiesReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadTagReplacer.cs
  src/Html2Markdown/Replacement/Heading.cs
  src/Html2Markdown/Replacement/HeadingReplacementGroup.cs
  src/Html2Markdown/Replacement/HeadingTagReplacer.cs
  src/Html2Markdown/Replacement/HorizontalRuleTagReplacer.cs
  src/Html2Markdown/Replacement/HtmlCommentReplacer.cs
  src/Html2Markdown/Replacement/HtmlEntitiesReplacer.cs
  src/Html2Markdown/Replacement/HtmlListReplacer.cs
  src/Html2Markdown/Replacement/HtmlParser.cs
  src/Html2Markdown/Replacement/HtmlTagReplacer.cs
  src/Html2Markdown/Replacement/IllegalHtmlReplacementGroup.cs
  src/Html2Markdown/Replacement/ImageTagReplacer.cs
  src/Html2Markdown/Replacement/LayoutReplacementGroup.cs
  src/Html2Markdown/Replacement/LinkTagReplacer.cs
  src/Html2Markdown/Replacement/MetaTagReplacer.cs
  src/Html2Markdown/Replacement/ParagraphTagReplacer.cs
  src/Html2Markdown/Replacement/PatternReplacer.cs
  src/Html2Markdown/Replacement/PreTagReplacer.cs
  src/Html2Markdown/Replacement/ScriptTagReplacer.cs
  src/Html2Markdown/Replacement/StrongTagReplacer.cs
  src/Html2Markdown/Replacement/TextFormattingReplacementGroup.cs
  src/Html2Markdown/Replacement/TitleTagReplacer.cs
  src/Html2Markdown/Scheme/Markdown.cs
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsABoldTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAMultilineOrderedListWithNestedParagraphsAndCodeElement_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAParagraphTagAfterAList_ThenThereShouldBeAppropriateSpacing.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAStrongTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithANestedUnorderedList_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/CommonMarkSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithNestedParagraphs_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsABoldTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAMultilineOrderedListWithNestedParagraphsAndCodeElement_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAParagraphTagAfterAList_ThenThereShouldBeAppropriateSpacing.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAStrongTagWithProperties_ThenConvertToMarkDownDoubleAsterisks.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithANestedUnorderedList_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.Convert_WhenThereIsAnOrderedListWithNestedParagraphs_ThenReplaceWithMarkdownLists.verified.txt
  test/Html2Markdown.Test/MarkdownSchemeConverterTest.cs
Labels: 30 min review

#367 Merge master into develop branch
  CHANGELOG.md
  semver.json
Labels: 1 min review
